### ISSUE TITLE
Add command to end job

### ISSUE THREAD

**Issue by antiguru** [strymon-system/strymon-core#12]
Currently, Strymon exposes a submit API but once a job is running, there does not seem to be an easy way to stop it again. It would be nice if a job can be released given its (query?) id:
`./bin/strymon kill --query 0`

**Comment by gandro** [comment]
With #3 merged, this can now be implemented, though it needs som additional plumbing. The approach would be as follows:

 1. The executors need to keep the `Child` handle around, e.g. in a `HashMap<QueryId, Child>`
 2. The termination request are sent to the to the coordinator, which in turn forwards it to all executors
 3. The executors removes the `Child` handle from the hashmap and drop it (resulting in a `kill(pid)` on Unix)

There are probably some ownership complications right now, as the `Child` handle need to be registered in tokio to get notifications for `SIGCHILD`, but this can probably be worked around.
