### ISSUE TITLE
Subscriber should merge upper frontiers from multiple topics

### ISSUE THREAD

**Issue by gandro** [strymon-system/strymon-core#29]
The current implementation of the new publisher framework in `strymon_job` (landed in PR #25) introduces an "upper frontier" for tracking active epochs. An epoch is considered active if the the publisher has observed tuples with that epoch in the past. The upper frontier represents an upper bound (i.e. the maximal antichain) of the active epochs at the time the subscriber connected. 

Currently, this "upper frontier" snapshot is used as a subscriber-side filter: The subscriber ignores any tuples where`t <= t_u | t_u was an element of the upper frontier at subscription time`. This works fine when reading from a single topic.

When reading from multiple topic however, the situation is less clear. Currently, each subscription filters its own topic, i.e. the various initial upper frontiers are not merged. This means that some subscriptions might let through epochs which are filtered out in others. This is probably wrong e.g. in cases where the subscriptions are for different partitions of the upstream dataflow. In these cases, it seems like we want to merge the upper frontiers. The resulting behaviour will be that if an epoch was active in one partition, it is filtered out in all other partitions as well.

Note that the "lower frontier" is already being merged in the current system (i.e. a notification for a certain epoch is only delivered once all topics have closed the epoch), due to the fact that we offload this task to Timely's capability tracking mechanism.

**Comment by utaal** [comment]
Are there cases in which subscribers subscribe to topics that are not all partitions of the same stream? if not, the most non-surprising behavior seems to be the one you propose; custom subscribers may be written if this is not the desired behaviors.

Alternatively, is it possible to build the subscribers per-topic and then have a subscriber-wrapper that behaves as you propose?

**Comment by gandro** [comment]
This is now implemented in #30
