### ISSUE TITLE
Support stable Rust

### ISSUE THREAD

**Issue by gandro** [strymon-system/strymon-core#4]
Currently the last remaining blocker for making `strymon_runtime` compile on stable Rust is the use of the `type_name` intrinsic in topic schemas: https://github.com/strymon-system/strymon-core/blob/c9ed415c2275f84844d8fcbed039df4486cdcbf7/src/strymon_runtime/src/model/mod.rs#L28

Short-term, we should replace the intrinsic with the [`named_type`](https://docs.rs/named_type/0.1.3/named_type/) crate.

Long-term, we need a better story for defining equality on a topic schema. In the old Abomonation-based pub/sub, the `TopicType` struct under question used to be a wrapper around `std::any::TypeId` which was intended to be a rough safety-check to avoid accidentally decoding incompatible Abomonation-encoded data types.

**Comment by gandro** [comment]
Quick observation: Unfortunately the NamedType trait does not seem to be implemented for even the most basic types like `u32` or `String`, which we would need.

**Comment by skade** [comment]
One way here would be to introduce a trait named `TopicName`, which has an interface similar to NamedType and is implemented for all NamedType types. It could then be implemented for an additional number of basic types.

I still haven't fully understood why topics must be named by type, so another stategy there might also be worthwhile.

**Comment by gandro** [comment]
To elaborate a bit, the purpose of the `TopicSchema` (i.e. the only place where a `TopicType` is used) is supposed to contain information about the (data) type of a topic. This "information" is currently just the data type name (as a string), but it used to also contain a type id, and we have some ideas to extend it again in the future.

The first use-case was to ensure that the user does not try to subscribe to a topic with the wrong type. This was important when we used Abomonation for the pub/sub, since deserializing the wrong type would lead to undefined behaviour.  For this, we just need to be able to tell two `TopicType`s are the same or not, and an opaque identifier was enough for this. This was achieved through with a `std::any::TypeId`, but is now obsolete (since we switched to msgpack/serde, which performs these checks itself) and most of the code for this has been removed.

The second purpose of the `TopicSchema` is to give users inspecting the system (e.g. with `strymon status`) some information about what the currently existing topics contain. This is the reason why we also currently keep the type name, it's mostly just to improve the user experience. Considering this is the only remaining nighty feature we depend on, I'm okay with maybe just dropping this feature (or hiding it behind a feature-flag). Adding an additional trait implementation "just" for this seems a bit too much of a burden.

As for where the future plans lie with the `TopicSchema`, is that it might become useful for potential future work where we want to implement automated job composition in Strymon. For this we would a machine-readable representation of the topic type (i.e. a schema). We have however never gotten around to implement this. If we had this, we could however also easily derive a human-readable representation as well. I'm wondering if we could extract the type name from serde's Deserialize trait, which is already a requirement.

**Comment by skade** [comment]
I'm still confused why topics get an automatically assigned name, anyways. For debugging purposes, I'd much rather prefer to give the name myself.

**Comment by frankmcsherry** [comment]
I think the gist is that a topic has a pile of data associated with it, and you want to be able to explain that the data are e.g. `(usize, String)` as opposed to `Vec<(bool, Vec<u32>)>`, or whatever the types happen to be. So, you might like an output like:

```
current tables / topics:
your_name1: type = Table<(usize, String)>
your_name2: type = Table<Vec<(bool, Vec<u32>)>>
```

At least, I'm guessing that is the need based on what I know. Correct as appropriate! :D

**Comment by gandro** [comment]
Yes! The topic _name_ and the topic _type_ are two different things. The name string can be freely chosen, the type is determined when you publish a Timely stream.

To give a concrete example, consider the following line in the topology generator:
```rust
let mut input = root.dataflow::<u64, _, _>(|scope| {
    let (input, stream) = scope.new_input();

    coord.publish_collection("topology", &stream, Partition::Merge)
        .expect("failed to publish topology updates");

    input
});
```

`stream` is of type `Stream<(topology_generator::Entity, i32)>`, so here the published topic has the name "topology", and it's item type is `topology_generator::Entity` (i32 encodes the diff). Thus, the output of `strymon status` is as follows:

```
$ ./bin/strymon status
Coordinator: localhost:9189
 Executor 0: host="localhost"
  Query 0: name=<unnamed>, workers=1
   Publication on Topic 6: name="topology", schema=Collection(item="topology_generator::Entity")
```

The `type_name()` intrinsic is only used to be able to print the thing after "item=". If we'd feature gate the intrinsic call and replace it with `"<unknown>"`, it would print

```
   Publication on Topic 6: name="topology", schema=Collection(item="<unknown>")
```
