### ISSUE TITLE
bin: locate_binary does not exit cleanly on error

### ISSUE THREAD

**Issue by antiguru** [strymon-system/strymon-core#7]
The `bin/start-strymon.sh` command uses `locate_binary` from `.common.sh` to locate the strymon binary. The function checks if the command exists and exists if it doesn't. However, it is designed to be called in a subprocess and thus exit will not do the right thing, i.e. it only exits the subprocess. See https://github.com/strymon-system/strymon-core/blob/master/bin/.common.sh#L20

The solution here is to check the rc on the caller side and propage the exit condition.

**Comment by gandro** [comment]
Hm. Supposedly, [`set -e`](https://www.gnu.org/software/bash/manual/bashref.html#The-Set-Builtin) was to take care of this, as it also is supposed to apply to subshells. And while `set -e` reliably causes an early exit when called as `BINARY=$(locate_binary)`, it does not do it for the nested `BINARY="$(abspath "$(locate_binary)")"`
